name: rd-gowinrm-plugin
version: 0.1.0
rundeckPluginVersion: 1.0
author: Gonzalo Peci
date: 15.01.2016
providers:
  - name: Go-WinRM-Exec
    title: WinRM Executor
    description: Executing Scripts or commands on remote windows computer
    service: NodeExecutor
    plugin-type: script
    script-file: go_winrm_exec
#    script-args: ${config.realm} ${config.username} ${config.password} ${node.hostname} ${exec.command}
    interpreter-args-quoted: true
    config:
      - name: krb5_realm
        title: Kerberos Realm
        type: String
        required: false
        description: "Kerberos Realm FQDN in capital letters"
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "krb5_realm"
      - name: user
        title: Username
        description: "Username in DOMAIN\\name form"
        type: String
        required: false
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "user"
      - name: pass
        title: Password
        description: `Path to the Password to use within Rundeck Storage. E.g. "keys/path/my.password". Can be overridden by a Node attribute named 'winrm-password-storage-path'.`
        type: String
        required: false
        scope: Instance
        renderingOptions:
          displayType: PASSWORD
          selectionAccessor: STORAGE_PATH
          instance-scope-node-attribute: "winrm-password-storage-path"
      - name: authtype
        title: Auth type
        description: "Autentification type"
        type: Select
        values: "kerberos, plaintext, ssl"
        default: "plaintext"
        required: true
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "authtype"
      - name: allowoverride
        title: Allow Override
        description: "Gives possibility to override hostname, username (and password) in job options"
        type: Select
        values: "none, host, user, all"
        default: "none"
        required: true
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "allowoverride"
      - name: winrmport
        title: WinRM port
        description: "WinRM port (Default: 5985/5986 for http/https)"
        type: String
        default: "5985"
        required: true
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "winrmport"
      - name: shell
        title: Shell
        description: "Windows interpreter"
        type: Select
        values: "cmd, powershell, wql"
        default: 'powershell'
        required: true
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "shell"
      - name: winrmtimeout
        title: WinRM timeout
        description: "timeout in seconds default: 60"
        type: Integer
        required: false
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "winrmtimeout"
  - name: Go-WinRM-Copy
    title: WinRM File Copier
    service: FileCopier
    plugin-type: script
    script-file: go_winrm_cp
    script-args: ${node.hostname} ${file-copy.file} ${file-copy.destination}
    config:
      - name: krb5_realm
        title: Kerberos Realm
        type: String
        required: false
        description: "Kerberos Realm FQDN in capital letters"
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "krb5_realm"
      - name: user
        title: Username
        type: String
        required: false
        description: "Username in DOMAIN\\name form"
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "user"
      - name: pass
        title: Password
        type: String
        required: false
        description: "Password"
        scope: Instance
        renderingOptions:
          displayType: PASSWORD
          selectionAccessor: STORAGE_PATH
      - name: authtype
        title: Auth type
        description: "Autentification type"
        type: Select
        values: "kerberos, plaintext, ssl"
        default: "plaintext"
        required: true
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "authtype"
      - name: allowoverride
        title: Allow Override
        description: "Gives possibility to override hostname, username (and password) in job options"
        type: Select
        values: "none, host, user, all"
        default: "none"
        required: true
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "allowoverride"
      - name: winrmport
        title: WinRM port
        description: "WinRM port (Default: 5985/5986 for http/https)"
        type: String
        default: "5985"
        required: true
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "winrmport"
      - name: shell
        title: Shell
        description: "Windows interpreter. Should be same as in Executor"
        type: Select
        values: "cmd, powershell, wql"
        default: 'powershell'
        required: true
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "shell"
      - name: winrmtimeout
        title: WinRM timeout
        description: "timeout in seconds default: 60"
        type: Integer
        required: false
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "winrmtimeout"

